{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.global.zipkinBaseURL }}
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eurekaServerURL }}
  MYSQL_ROOT_USER: {{ .Values.global.mysqlRootUser }}
  MYSQL_ROOT_PASSWORD: "{{ .Values.global.mysqlRootPassword }}"
  MYSQL_HOST: {{ .Values.global.mysqlHost }}
  MYSQL_PORT: "{{ .Values.global.mysqlPort }}"
{{- end -}}