global:
  configMapName: eazybankprod-configmap
  zipkinBaseURL: http://zipkin:9411/api/v2/spans
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://discoveryserver:8761/eureka/
  volumeName: mysql-pv-volume
  volumeClaimName: mysql-pv-claim
  mysqlHost: mysql
  mysqlPort: 3306
  mysqlRootUser: root
  mysqlRootPassword: 12345678
  keyCloakURL: http://my-release-keycloak:80/realms/master/protocol/openid-connect/certs