# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: configserver-deployment
deploymentLabel: configserver

replicaCount: 1

image:
  repository: truongngo1993/eazybank-config-server
  tag: latest

containerPort: 8071

service:
  type: LoadBalancer
  port: 8071
  targetPort: 8071

config_enabled: false
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false
appname_enabled: false
database_enabled: false
is_mysql: false
auth_enabled: false