{{- define "common.persistentvolumeclaim" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.volumeClaimName }}
spec:
  storageClassName: {{ .Values.volumeStorageClassName }}
  accessModes:
    - {{ .Values.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumeStorage }}
{{- end -}}