apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: truongngo1993/eazybank-loans:latest
          ports:
            - containerPort: 8100
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: LOANS_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: LOANS_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MYSQL_ROOT_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100