apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: truongngo1993/eazybank-api-gateway:latest
          ports:
            - containerPort: 8765
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: API_GATEWAY_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: http://keycloak:8080/realms/master/protocol/openid-connect/certs
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765